#!/usr/bin/env python3
"""Generate original geometric test footage and local speech, never production AD."""
import json, subprocess, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MEDIA = ROOT / 'media' / 'fixture'
MEDIA.mkdir(parents=True, exist_ok=True)
def run(args):
    subprocess.run(args, check=True, stdout=subprocess.DEVNULL)
def duration(path):
    return float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',str(path)], text=True))
def speech(name, text):
    with tempfile.TemporaryDirectory(prefix='sema-speech-') as scratch:
        aiff=Path(scratch)/'speech.aiff'
        run(['/usr/bin/say','-v','Samantha','-r','190','-o',str(aiff),text])
        dest=MEDIA/f'{name}.mp3'
        run(['ffmpeg','-hide_banner','-loglevel','error','-y','-i',str(aiff),'-ar','44100','-ac','1','-c:a','libmp3lame','-b:a','128k',str(dest)])
    return {'text':text,'audio':f'media/fixture/{name}.mp3','duration':duration(dest)}

first={level:speech(f'envelope-{level}',text) for level,text in {
    'essential':'The envelope is hidden.',
    'standard':'The red envelope is hidden inside the drawer.',
    'rich':'The red envelope disappears into a wooden drawer beneath the desk.'}.items()}
second={level:speech(f'door-{level}',text) for level,text in {
    'essential':'The door opens.',
    'standard':'The blue door opens. The drawer remains closed.',
    'rich':'The blue door opens onto a bright hallway. The wooden drawer stays closed.'}.items()}
# Recovery must be safe before the later door reveal.
r1=speech('recover-envelope','The red envelope is hidden inside the closed drawer beneath the desk.')
r2=speech('recover-door','The blue door has opened onto the hallway. The envelope is still hidden in the drawer.')
d1=speech('dialogue-one',"I'll be right back.")
d2=speech('dialogue-two','Where is it?')
assert d1['duration']+.1 < 2.3 and d2['duration']+7.2 < 9.3, 'Dialogue fixture exceeds planned intervals'
draw=("drawbox=x=90:y=350:w=520:h=30:color=0x887359:t=fill,"
      "drawbox=x=120:y=380:w=20:h=170:color=0x887359:t=fill,"
      "drawbox=x=560:y=380:w=20:h=170:color=0x887359:t=fill,"
      "drawbox=x=180:y=390:w=300:h=100:color=0x614e3c:t=fill,"
      "drawbox=x=300:y=428:w=60:h=8:color=0xddc4a5:t=fill,"
      "drawbox=x=275:y=280:w=155:h=68:color=0xec6262:t=fill:enable='lt(t,2)',"
      "drawbox=x=850:y=130:w=230:h=420:color=0x377ba1:t=fill,"
      "drawbox=x=875:y=150:w=180:h=380:color=0xf2d6a4:t=fill:enable='gte(t,9)',"
      "drawbox=x=845:y=130:w=35:h=420:color=0x377ba1:t=fill:enable='gte(t,9)'")
run(['ffmpeg','-hide_banner','-loglevel','error','-y','-f','lavfi','-i','color=c=0x162337:s=1280x720:r=24:d=15',
     '-i',str(MEDIA/'dialogue-one.mp3'),'-i',str(MEDIA/'dialogue-two.mp3'),
     '-filter_complex',f'[0:v]{draw}[v];[1:a]adelay=100:all=1[a1];[2:a]adelay=7200:all=1[a2];[a1][a2]amix=inputs=2:normalize=0,apad[a]',
     '-map','[v]','-map','[a]','-t','15','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart',str(MEDIA/'film.mp4')])
asset={'id':'red-envelope-fixture','version':'fixture-1','title':'The red envelope','duration':15,
       'video':'media/fixture/film.mp4','reviewStatus':'fixture',
       'synopsis':'Fifteen seconds of original geometric test footage: an envelope disappears, then a door opens.',
       'credits':'Original procedural footage (tools/generate-fixture.py). Engineering fixture; narration is a local test voice.','rights':'Original procedural footage generated by tools/generate-fixture.py. Local macOS Samantha narration for engineering tests only; not approved for submission.',
       'scenes':[{'id':'desk','start':0,'end':8.8},{'id':'door','start':8.8,'end':15}],
       'dialogue':[{'start':.1,'end':.1+d1['duration']},{'start':7.2,'end':7.2+d2['duration']}],
       'events':[{'id':'envelope-hidden','scene':'desk','availableAt':2,'critical':True,'recovery':r1},
                 {'id':'door-open','scene':'door','availableAt':9,'critical':True,'recovery':r2}],
       'cues':[{'id':'envelope','events':['envelope-hidden'],'start':2.3,'end':7,'margin':.2,'variants':first},
               {'id':'door','events':['door-open'],'start':9.3,'end':14.9,'margin':.2,'variants':second}]}
(MEDIA/'package.json').write_text(json.dumps(asset,indent=2)+'\n')
print('Generated fixture and measured narration durations:')
for c in asset['cues']:
    for level,v in c['variants'].items():
        assert v['duration']+2*c['margin'] <= c['end']-c['start'], (c['id'],level,'does not fit')
        print(f"  {c['id']}/{level}: {v['duration']:.3f}s")
